Parameters:
        BucketName:
                Description: Name your jason bucket
                Type: String

Resources:
        S3Bucket:
                Type: AWS::S3::Bucket
                Properties:
                        AccessControl: Private
                        BucketName: !Ref BucketName
                        BucketEncryption:
                                        ServerSideEncryptionConfiguration:
                                                - ServerSideEncryptionByDefault:Pa
                                        SSEAlgorithm: AES256
